config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:8080'
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
    - name: 'Sessions Flow (Register y login)'
        - log: 'Creamos un usuario de prueba'
        - get:
          url: /pruebas/test/user
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
        -log: 'Registramos el usuario de prueba'
        - post:
          url: /pruebas/test/user/register
          json:
            first_name: "$first_name"
            last_name: "$last_name"
            email: "$email"
            password: "$password"
        - log: 'logueamos a usuario de prueba'
        - post:
          url: /pruebas/test/user/login
          